[package]
name = "ghteam-auth"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]

[dependencies]
clap = "2.29.0"
toml = "0.4.5"
reqwest = "0.8.1"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
glob = "0.2.11"
libc = "0.2.33"
lazy_static = "1.0.0"
nix = "0.9.0"

[[bin]]
name = "ghteam-auth"
path = "src/main.rs"

[lib]
name = "nss_ghteam"
path = "src/lib.rs"
crate-type = ["cdylib"]
