[package]
name = "ghteam-auth"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]

[dependencies]
clap = "2.26.0"
toml = "0.4.0"
reqwest = "0.7.3"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
glob = "0.2.11"
libc = "0.2"
lazy_static = "0.2.8"
nix = "0.9.0"

[[bin]]
name = "ghteam-auth"
path = "src/main.rs"

[lib]
name = "nss_ghteam"
path = "src/lib.rs"
crate-type = ["dylib"]
