[package]
name = "sectora"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]
build = "build.rs"

[dependencies]
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
glob = "0.3"
libc = "0.2"
lazy_static = "1.3"
nix = "0.13"
http = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
structopt = "0.2"

# https://github.com/nix-rust/nix/issues/1057
[patch.crates-io]
nix = { git = "https://github.com/nix-rust/nix/", rev = "196b05b5c7b" }

[[bin]]
name = "sectora"
path = "src/main.rs"

[lib]
name = "nss_sectora"
path = "src/lib.rs"
crate-type = ["cdylib"]
