[package]
name = "ghteam-auth"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]

[dependencies]
hyper = "0.10.9"
hyper-rustls = "0.3.3"
clap = "2.19"
toml = "0.4.0"
reqwest = "0.5.1"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
glob = "0.2.11"
