[package]
name = "sectora"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]
build = "build.rs"

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
glob = "0.2"
libc = "0.2"
lazy_static = "1.0"
nix = "0.10"
hyper = "0.11"
hyper-rustls = "0.12"
tokio-core = "0.1"
futures = "0.1"
structopt = "0.2"

[[bin]]
name = "sectora"
path = "src/main.rs"

[lib]
name = "nss_sectora"
path = "src/lib.rs"
crate-type = ["cdylib"]
