[package]
name = "sectora"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]

[dependencies]
toml = "0.4.5"
serde = "1.0.38"
serde_derive = "1.0.38"
serde_json = "1.0.14"
glob = "0.2.11"
libc = "0.2.40"
lazy_static = "1.0.0"
nix = "0.10.0"
hyper = "0.11.25"
hyper-rustls = "0.12.0"
tokio-core = "0.1.16"
futures = "0.1.17"
structopt = "0.2"

[[bin]]
name = "sectora"
path = "src/main.rs"

[lib]
name = "nss_sectora"
path = "src/lib.rs"
crate-type = ["cdylib"]
