version: 2
jobs:
  build:
    working_directory: /tmp/sectora
    docker:
      - image: rust:1.32.0-stretch
    steps:
      - checkout
      - run: cargo build

  build-arm:
    working_directory: /tmp/sectora
    docker:
      - image: yasuyuky/rust-arm:1.32.0
    steps:
      - checkout
      - run: cargo build --target=arm-unknown-linux-gnueabihf
