version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "yasuyuky"
  - package_manager: "docker"
    directory: "/test/client"
    update_schedule: "daily"
    default_reviewers:
      - "yasuyuky"
  - package_manager: "docker"
    directory: "/test/json-server"
    update_schedule: "daily"
    default_reviewers:
      - "yasuyuky"
